[package]
name = "swarmit-tui"
version.workspace = true
edition.workspace = true

[dependencies]
swarmit-core = { workspace = true }
chrono = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
notify-debouncer-mini = { workspace = true }
notify = { workspace = true }
anyhow = { workspace = true }
catppuccin = { workspace = true }
terminal-colorsaurus = { workspace = true }
bat = { version = "0.26", default-features = false, features = ["regex-fancy"] }
syntect = { version = "5", default-features = false }

[dev-dependencies]
tempfile = "3"
