[package]
name = "swarmit-tui"
version.workspace = true
edition.workspace = true

[dependencies]
swarmit-core = { workspace = true }
chrono = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
notify-debouncer-mini = { workspace = true }
notify = { workspace = true }
anyhow = { workspace = true }
catppuccin = { workspace = true }
terminal-colorsaurus = { workspace = true }
